services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bizcore-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    container_name: bizcore-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: bizcore-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: bizcore-portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yml:/etc/tempo.yaml
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - tempo

  minio:
    image: minio/minio:latest
    container_name: bizcore-minio
    ports:
      - "9005:9000" # API (Changed from 9000 to 9005 to avoid conflict with Portainer)
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-setup:
    image: minio/mc:latest
    container_name: bizcore-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      - /bin/sh
      - -c
      - |
        until /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin; do echo 'Waiting for MinIO...' && sleep 1; done;
        
        # Private bucket for ERP data
        if ! /usr/bin/mc ls local/bizcore-uploads > /dev/null 2>&1; then
          /usr/bin/mc mb local/bizcore-uploads;
        fi
        /usr/bin/mc anonymous set private local/bizcore-uploads;

        # Public bucket for avatars and public assets
        if ! /usr/bin/mc ls local/public-files > /dev/null 2>&1; then
          /usr/bin/mc mb local/public-files;
        fi
        /usr/bin/mc anonymous set public local/public-files;

        echo 'MinIO setup completed successfully with private and public buckets.';
        exit 0;

  gateway-api:
    image: bizcore-gateway-api
    container_name: bizcore-gateway
    build:
      context: .
      dockerfile: src/Gateway/Gateway.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ReverseProxy__Clusters__invoice-cluster__Destinations__d1__Address=http://invoice-api:8080
      - ReverseProxy__Clusters__payment-cluster__Destinations__d1__Address=http://payment-api:8080
      - ReverseProxy__Clusters__report-cluster__Destinations__d1__Address=http://report-api:8080
      - ReverseProxy__Clusters__orchestration-cluster__Destinations__d1__Address=http://orchestration-api:8080
      - ReverseProxy__Clusters__admin-cluster__Destinations__d1__Address=http://admin-api:8080
      - ReverseProxy__Clusters__audit-cluster__Destinations__d1__Address=http://audit-api:8080
      - ReverseProxy__Clusters__file-cluster__Destinations__d1__Address=http://file-api:8080
      - Loki__Url=http://loki:3100
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ServiceName=Gateway.API
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - invoice-api
      - payment-api
      - report-api
      - orchestration-api
      - admin-api
      - audit-api
      - file-api
      - loki

  invoice-api:
    image: bizcore-invoice-api
    build:
      context: .
      dockerfile: src/Services/Invoice/Invoice.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=InvoiceDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ServiceName=Invoice.API
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      - loki

  payment-api:
    image: bizcore-payment-api
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=PaymentDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ServiceName=Payment.API
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      - loki

  report-api:
    image: bizcore-report-api
    container_name: bizcore-report
    build:
      context: .
      dockerfile: src/Services/Report/Report.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=ReportDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ServiceName=Report.API
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      - loki

  orchestration-api:
    image: bizcore-orchestration-api
    container_name: bizcore-orchestration
    build:
      context: .
      dockerfile: src/Services/Orchestration/Orchestration.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=OrchestrationDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ServiceName=Orchestration.API
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      - loki

  admin-api:
    image: bizcore-admin-api
    container_name: bizcore-admin
    build:
      context: .
      dockerfile: src/Services/Admin/Admin.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=AdminDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ServiceName=Admin.API
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      # - loki

  audit-api:
    image: bizcore-audit-api
    container_name: bizcore-audit
    build:
      context: .
      dockerfile: src/Services/Audit/Audit.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=AuditDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ServiceName=Audit.API
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
      - Retention__HotDays=180
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      - loki

  file-api:
    image: bizcore-file-api
    container_name: bizcore-file
    build:
      context: .
      dockerfile: src/Services/File/File.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Minio__Endpoint=minio:9000
      - Minio__ExternalEndpoint=http://localhost:9005
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin
      - Minio__BucketName=bizcore-uploads
      - Minio__PublicBucketName=public-files
      - Minio__UseSSL=false
      - Loki__Url=http://loki:3100
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ServiceName=File.API
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - rabbitmq
      - redis
      - minio
      - loki

  web-ui:
    image: bizcore-web-ui
    container_name: bizcore-web
    build:
      context: ./src/WebUI
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - gateway-api

volumes:
  portainer_data:
  minio_data:
