services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bizcore-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bizcore-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: bizcore-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: bizcore-portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  # loki:
  #   image: grafana/loki:2.9.0
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml

  # promtail:
  #   image: grafana/promtail:2.9.0
  #   container_name: promtail
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/containers:/var/lib/docker/containers
  #     - ./promtail-config.yml:/etc/promtail/config.yml
  #   command: -config.file=/etc/promtail/config.yml

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - loki

  gateway-api:
    image: bizcore-gateway-api
    container_name: bizcore-gateway
    build:
      context: .
      dockerfile: src/Gateway/Gateway.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ReverseProxy__Clusters__invoice-cluster__Destinations__d1__Address=http://invoice-api:8080
      - ReverseProxy__Clusters__payment-cluster__Destinations__d1__Address=http://payment-api:8080
      - ReverseProxy__Clusters__report-cluster__Destinations__d1__Address=http://report-api:8080
      - ReverseProxy__Clusters__orchestration-cluster__Destinations__d1__Address=http://orchestration-api:8080
      - ReverseProxy__Clusters__identity-cluster__Destinations__d1__Address=http://identity-api:8080
      - ReverseProxy__Clusters__audit-cluster__Destinations__d1__Address=http://audit-api:8080
      - Loki__Url=http://loki:3100
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - invoice-api
      - payment-api
      # - report-api
      # - orchestration-api
      - identity-api
      - audit-api
      # - loki

  invoice-api:
    image: bizcore-invoice-api
    build:
      context: .
      dockerfile: src/Services/Invoice/Invoice.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=InvoiceDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      # - loki

  payment-api:
    image: bizcore-payment-api
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=PaymentDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      # - loki

  # report-api:
  #   image: bizcore-report-api
  #   container_name: bizcore-report
  #   build:
  #     context: .
  #     dockerfile: src/Services/Report/Report.API/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Server=sql-server;Database=ReportDb_v2;User Id=sa;Password=Password123!;TrustServerCertificate=True
  #     - ConnectionStrings__Redis=redis:6379
  #     - RabbitMQ__Host=rabbitmq
  #     - Loki__Url=http://loki:3100
  #     - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
  #   depends_on:
  #     - sql-server
  #     - rabbitmq
  #     - redis
  #     - loki

  # orchestration-api:
  #   image: bizcore-orchestration-api
  #   container_name: bizcore-orchestration
  #   build:
  #     context: .
  #     dockerfile: src/Services/Orchestration/Orchestration.API/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:8080
  #     - ConnectionStrings__DefaultConnection=Server=sql-server;Database=OrchestrationDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
  #     - ConnectionStrings__Redis=redis:6379
  #     - RabbitMQ__Host=rabbitmq
  #     - Loki__Url=http://loki:3100
  #     - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
  #   depends_on:
  #     - sql-server
  #     - rabbitmq
  #     - redis
  #     - loki

  identity-api:
    image: bizcore-identity-api
    container_name: bizcore-identity
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=IdentityDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      # - loki

  audit-api:
    image: bizcore-audit-api
    container_name: bizcore-audit
    build:
      context: .
      dockerfile: src/Services/Audit/Audit.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=AuditDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__Host=rabbitmq
      - Loki__Url=http://loki:3100
      - Jwt__SecretKey=BizcoreERPSecretKeyMustBeVeryLongAndSecure!!!
      - Retention__HotDays=180
    depends_on:
      - sql-server
      - rabbitmq
      - redis
      # - loki

  web-ui:
    image: bizcore-web-ui
    container_name: bizcore-web
    build:
      context: ./src/WebUI
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - gateway-api

volumes:
  portainer_data:

