version: '3.4'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway-api:
    image: bizcore-gateway-api
    build:
      context: .
      dockerfile: src/Gateway/Gateway.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__invoice-cluster__Destinations__d1__Address=http://invoice-api:8080
      - ReverseProxy__Clusters__payment-cluster__Destinations__d1__Address=http://payment-api:8080
      - ReverseProxy__Clusters__report-cluster__Destinations__d1__Address=http://report-api:8080
    depends_on:
      - invoice-api
      - payment-api
      - report-api

  invoice-api:
    image: bizcore-invoice-api
    build:
      context: .
      dockerfile: src/Services/Invoice/Invoice.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=InvoiceDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - sql-server
      - rabbitmq

  payment-api:
    image: bizcore-payment-api
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=PaymentDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - sql-server
      - rabbitmq

  report-api:
    image: bizcore-report-api
    build:
      context: .
      dockerfile: src/Services/Report/Report.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=ReportDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - sql-server
      - rabbitmq
