<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.9.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="TngTech.ArchUnitNET" Version="0.13.3" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" Version="0.13.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Bizcore.BuildingBlocks\Bizcore.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Services\Invoice\Invoice.API\Invoice.API.csproj" />
    <ProjectReference Include="..\..\Services\Payment\Payment.API\Payment.API.csproj" />
    <ProjectReference Include="..\..\Services\Report\Report.API\Report.API.csproj" />
    <ProjectReference Include="..\..\Services\Orchestration\Orchestration.API\Orchestration.API.csproj" />
    <ProjectReference Include="..\..\Services\Admin\Admin.API\Admin.API.csproj" />
    <ProjectReference Include="..\..\Services\Audit\Audit.API\Audit.API.csproj" />
    <ProjectReference Include="..\..\Services\File\File.API\File.API.csproj" />
    <ProjectReference Include="..\..\Services\Customer\Customer.API\Customer.API.csproj" />
  </ItemGroup>

</Project>